config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

# settings
DEBUG = settings.DEBUG
INSTALLED_APPS = settings.INSTALLED_APPS
ADMIN_URL = settings.ADMIN_URL
MEDIA_URL = settings.MEDIA_URL
MEDIA_ROOT = settings.MEDIA_ROOT

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # Favicon
    path("favicon.ico", RedirectView.as_view(url="/static/images/icons/favicon.ico")),
    # Django administration
    path(ADMIN_URL, admin.site.urls),
    # REST framework's login and logout views
    path("api-auth/", include("rest_framework.urls")),
    # DRF Spectacular
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
    # Project
    # core
    path("api/core/", include("project.core.urls", namespace="core")),
]

# for development environment only
if DEBUG:
    # Serve media files using static app
    from django.conf.urls.static import static

    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

    #  Activate Django debug toolbar
    if "debug_toolbar" in INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            path(
                "__debug__/",
                include(debug_toolbar.urls),
            )
        ]

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path(
            "500/",
            default_views.server_error,
        ),
    ]

project/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("ping/", views.ping, name="ping"),
    path("upload/", views.image_upload, name="upload"),
]

project/core/models.py
from django.db import models

# Create your models here.

project/core/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from django.http import HttpRequest
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage


@api_view(http_method_names=["GET"])
def ping(request: HttpRequest):
    """
    A view function for handling ping requests.

    This function responds to HTTP GET requests by returning a JSON response
    with a "pong" message, indicating that the server is up and running.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        Response: A JSON response with a "ping" key and "pong" value.
    """
    # Create a JSON response with a "ping" key and "pong" value
    response_data = {"ping": "pong"}
    # Return the response with HTTP status code 200 OK
    return Response(data=response_data, status=status.HTTP_200_OK)

def image_upload(request):
    """
    View function for handling image uploads.

    Args:
        request (HttpRequest): The request object sent by the client.

    Returns:
        HttpResponse: Rendered HTML response.
    """

    # Check if the request method is POST and an image file is included in the request.
    if request.method == "POST" and request.FILES["image_file"]:
        # Get the uploaded image file from the request.
        image_file = request.FILES["image_file"]

        # Initialize a FileSystemStorage object to handle file storage.
        fs = FileSystemStorage()

        # Save the uploaded image file to the file system and get the filename.
        filename = fs.save(image_file.name, image_file)

        # Get the URL of the saved image.
        image_url = fs.url(filename)

        # Print the image URL for debugging purposes.
        print(image_url)

        # Render the upload.html template with the image URL passed as context data.
        return render(request, "core/upload.html", {"image_url": image_url})

    # else if the request method is not POST
    return render(request, "core/upload.html")

project/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}
  CSRF &vert; 403 &ndash; Forbidden
{% endblock title %}
{% block content %}
  <h1>403 &ndash; Forbidden</h1>
  <p>
    {% if exception %}{{ exception }}{% endif %}
    <hr />
    <strong>CSRF Verification failed. Request aborted.</strong>
  </p>
{% endblock content %}

project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Welcome to Django REST Framework
      {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
  </head>
  <body>
    <!-- Navbar -->
    {% include 'partials/_navbar.html' %}

    <!-- content -->
    {% block content %}
    {% endblock content %}
    <!-- script.js -->
    <script defer src="{% static 'js/app.js' %}"></script>
  </body>
</html>

project/templates/core/upload.html
{% extends 'base.html' %}

{% block content %}
  <form action="{% url 'core:upload' %}"
        method="post"
        enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="image_file" />
    <input type="submit" value="submit" />
  </form>
  {% if image_url %}
    <p>
      File uploaded at: <a href="{{ image_url }}">{{ image_url }}</a>
    </p>
  {% endif %}
{% endblock content %}

project/templates/pages/home.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <p>Welcome to Django REST Framework</p>
  </div>
{% endblock content %}

project/templates/partials/_navbar.html
{% load i18n %}

<nav>
  <div>
    <h1>[API NAME] &vert; Django REST Framework</h1>
  </div>
</nav>